encoding: UTF-8

# Site settings
title: Ke-Vinh Sagot's Portfolio
email: kvsagot@gmail.com
url: https://kavehes.github.io
description: "Level designer working at Ubisoft Annecy, currently on Riders Republic. Also Playdate developer when time allows"
keywords: "your keywords, separated by commas"
skills: "Game Dev - Level Designer - Pixel Artist sometimes"
meta_author: Ke-Vinh Sagot

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 51b180 #18bc9c #80B3FF
  primary-rgb: "81,177,128"  #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: France
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: mastodon
    url: https://mastodon.gamedev.place/@kavehes
  - title: twitter
    url: http://twitter.com/kvsagot
  - title: linkedin
    url: https://www.linkedin.com/in/ke-vinh-sagot/


# Postal address (add as many lines as necessary)
address:
  - line: 23bis Avenue des Romains
  - line: Annecy, 74000
  - line: France

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
